/**
 * list-tasks-ast.ts - AST-Powered Task Query Script (V4)
 *
 * This is an experimental version that uses AST-generated filter predicates
 * instead of inline filter logic. Benefits:
 *
 * 1. Single source of truth for filter logic (AST)
 * 2. Validated filters catch errors before script generation
 * 3. Consistent behavior across all query modes
 * 4. Smaller, cleaner scripts (~40% code reduction)
 * 5. Testable filter logic (unit tests for AST)
 *
 * Architecture:
 * - TaskFilter → buildAST() → FilterNode → emitOmniJS() → filter predicate
 * - Script generator embeds the predicate in OmniJS script
 *
 * @see docs/plans/2025-11-24-ast-filter-contracts-design.md
 */

import type { TaskFilter } from '../../../contracts/filters.js';
import {
  buildFilteredTasksScript,
  buildInboxScript,
  buildTaskByIdScript,
} from '../../../contracts/ast/script-builder.js';

/**
 * Build a V4 task query script using AST-generated filters
 *
 * This is the main entry point for AST-powered task queries.
 * It replaces the template-based approach in V3 with compile-time
 * filter generation.
 *
 * @param params - Query parameters including filter and options
 * @returns JXA script string ready for execution
 */
export function buildListTasksScriptV4(params: {
  filter: TaskFilter;
  fields?: string[];
  limit?: number;
  mode?: string;
}): string {
  const { filter, fields = [], limit = 50, mode = 'all' } = params;

  // Route to appropriate script builder based on mode
  let generatedScript;

  if (filter.id) {
    // ID lookup mode
    generatedScript = buildTaskByIdScript(filter.id, fields);
  } else if (mode === 'inbox' || filter.inInbox) {
    // Inbox mode
    const inboxFilter = { ...filter };
    delete inboxFilter.inInbox; // Already handled by inbox collection
    generatedScript = buildInboxScript(inboxFilter, { limit, fields });
  } else {
    // General filtered query
    generatedScript = buildFilteredTasksScript(filter, {
      limit,
      fields,
      includeCompleted: filter.completed === true,
    });
  }

  // Wrap the OmniJS script in JXA execution context
  return `
(() => {
  const app = Application('OmniFocus');

  try {
    // Execute AST-generated OmniJS script
    const omniJsScript = \`${escapeTemplateString(generatedScript.script)}\`;
    const resultJson = app.evaluateJavascript(omniJsScript);
    const result = JSON.parse(resultJson);

    // Return with metadata
    return JSON.stringify({
      tasks: result.tasks,
      metadata: {
        total_count: result.count,
        limit_applied: ${limit},
        mode: result.mode,
        filter_description: result.filter_description,
        optimization: 'ast_v4',
        architecture: 'ast_first'
      }
    });

  } catch (error) {
    return JSON.stringify({
      error: true,
      message: error.message || String(error),
      stack: error.stack || '',
      context: 'list_tasks_v4_ast'
    });
  }
})();
`;
}

/**
 * Escape template string for embedding in another template
 */
function escapeTemplateString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');
}

/**
 * Script template for V4 - kept for compatibility with buildScript pattern
 *
 * Note: This is a simplified template that gets the filter and options
 * injected at runtime. The actual filtering logic is generated by the
 * AST pipeline.
 */
export const LIST_TASKS_SCRIPT_V4 = `
(() => {
  const app = Application('OmniFocus');
  const filter = {{filter}};
  const fields = {{fields}} || [];
  const limit = {{limit}} || 50;

  // Note: This template is for documentation purposes.
  // Actual scripts are generated by buildListTasksScriptV4()
  // using the AST pipeline.

  try {
    // The AST-generated script would be embedded here
    // See buildListTasksScriptV4() for the actual implementation

    return JSON.stringify({
      error: true,
      message: 'Use buildListTasksScriptV4() instead of this template',
      context: 'list_tasks_v4_template'
    });

  } catch (error) {
    return JSON.stringify({
      error: true,
      message: error.message || String(error),
      context: 'list_tasks_v4_ast'
    });
  }
})();
`;

// Re-export for convenience
export { buildFilteredTasksScript, buildInboxScript, buildTaskByIdScript };
